services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: follow-the-wind-python-env:3.12
    container_name: python_env
    env_file:
      - ../.env-example
    working_dir: /workspace
    volumes:
      - ${APP_PATH:-../workspace}:/workspace
      - python_pip_cache:/root/.cache/pip
    tty: true
    stdin_open: true
    ports:
      - "8010:8000"
    command: tail -f /dev/null

volumes:
  python_pip_cache:
