services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: follow-the-wind-python-env:3.12
    container_name: python_env
    env_file:
      - .env
    working_dir: /workspace
    volumes:
      - ${APP_PATH}:/workspace
      - python_pip_cache:/root/.cache/pip
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    networks:
      - wind-dev-net

volumes:
  python_pip_cache:

networks:
  wind-dev-net:
    name: wind-dev-net
    external: true